{% set name = "codeentropy" %}
{% set version = "0.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  script: |
    python -m pip install . -vv --no-deps
    PIP_NO_INDEX=0 python -m pip install -vv --index-url https://pypi.org/simple "waterEntropy>=2,<3.0"
  entry_points:
    - CodeEntropy=CodeEntropy.cli:main

requirements:
  host:
    - python >=3.12
    - pip
    - flit-core >=4,<5
  run:
    - python >=3.12
    - numpy >=2.3.2,<2.5.0
    - mdanalysis >=2.10,<3.0
    - pandas >=2.3.3,<4.0
    - psutil >=5.9.4,<8.0
    - pyyaml >=6.0.3,<7.0
    - rich >=13.0.0,<16.0
    - python-art >=5.0,<7.0
    - networkx >=2.8,<4.0
    - requests >=2.32.2,<3.0
    - rdkit >=2025.3.4,<2026
    - dask >=2025.4.0,<2027.1.0
    - distributed >=2025.4.0,<2027.1.0
    - dask-jobqueue >=0.9.0,<1.0
    - numba >=0.63.0,<0.70

test:
  imports:
    - CodeEntropy
  commands:
    - CodeEntropy --help

about:
  home: https://github.com/CCPBioSim/CodeEntropy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  license_url: https://github.com/CCPBioSim/CodeEntropy/blob/main/LICENSE
  summary: Python package for calculating configurational entropy from molecular dynamics simulations using the multiscale cell correlation method.
  description: "CodeEntropy is a Python package for computing the configurational entropy of macromolecular systems using forces sampled from molecular dynamics (MD) simulations. It implements the multiscale cell correlation method to provide accurate and efficient entropy estimates, supporting a wide range of applications in molecular simulation and statistical mechanics."
  dev_url: https://github.com/CCPBioSim/CodeEntropy
  doc_url: https://codeentropy.readthedocs.io/en/latest/
  doc_source_url: https://github.com/CCPBioSim/CodeEntropy/blob/main/README.md
