name: CodeEntropy Daily Checks

on:
  schedule:
    - cron: '0 8 * * 1-5'
  workflow_dispatch:

concurrency:
  group: daily-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit:
    name: Daily unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2025, macos-15]
        python-version: ["3.12", "3.13", "3.14"]
    timeout-minutes: 30
    steps:
      - name: Checkout repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install CodeEntropy and its testing dependencies
        run: |
          pip install --upgrade pip
          pip install -e .[testing]

      - name: Run unit test suite
        run: pytest tests/unit -q
